"""
crs.py — Catalytic Reaction System (CRS), the standard object of RAF theory.

Definition (Veloz, "Decomposing Autocatalytic Sets through Chemical
Organization Theory", Sec. 3, following Hordijk & Steel 2004): a CRS is a
tuple Q = (M, R, C, F0) with species M, reactions R (each with reactants
supp(r) and products prod(r)), a catalysis assignment C: R -> 2^M
specifying the species that may catalyse each reaction, and a food set
F0 subset M assumed freely available.

This module is deliberately independent of cot_gen/pyCOT: it is the plain,
literature-standard object, so raf_algo.py can be validated against
hand-verifiable toy examples (and the paper's own worked Network N / N')
before anything COT-specific is built on top of it.
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Reaction:
    """
    reactants/products: the SETS supp(r)/prod(r) used by RAF conditions
    (Def 3.1) -- these are deliberately coefficient-blind, matching the
    paper's own observation that RAF-ness never looks at stoichiometric
    coefficients (Example 4.6: perturbing f+a->... to f+2a->... leaves the
    RAF-algebra layer completely unchanged; only the flux cone changes).

    reactant_coeffs/product_coeffs: OPTIONAL signed multiplicities, used
    only by the COT-translation/bridge layer (needs real coefficients to
    reproduce the self-maintenance LP, e.g. Example 4.6's f+2a->b+g).
    Default to 1 per species in `reactants`/`products` when omitted, which
    is exact for every RAF-algebra example (coefficients never matter
    there) and is overridden explicitly wherever a real coefficient > 1
    is needed for a stoichiometric/bridge-layer example or a real network.
    """
    name: str
    reactants: frozenset[str]
    products: frozenset[str]
    catalysts: frozenset[str]   # species that catalyze this reaction
    reactant_coeffs: dict[str, float] = field(default_factory=dict)
    product_coeffs: dict[str, float] = field(default_factory=dict)

    def coeff(self, species: str) -> float:
        """Net stoichiometric coefficient of `species` in this reaction (product - reactant)."""
        p = self.product_coeffs.get(species, 1.0 if species in self.products else 0.0)
        r = self.reactant_coeffs.get(species, 1.0 if species in self.reactants else 0.0)
        return p - r

    def __repr__(self) -> str:
        def fmt(coeffs, names):
            parts = []
            for s in sorted(names):
                c = coeffs.get(s, 1)
                parts.append(f"{c:g}{s}" if c != 1 else s)
            return "+".join(parts)
        r = fmt(self.reactant_coeffs, self.reactants)
        p = fmt(self.product_coeffs, self.products)
        c = ",".join(sorted(self.catalysts))
        return f"{self.name}: {r} -> {p}  [cat: {c}]"


@dataclass
class CRS:
    """
    species    : all molecule types appearing anywhere (reactants, products,
                 catalysts, or food).
    reactions  : dict[name -> Reaction].
    food       : frozenset of food-set species.
    """
    species: frozenset[str]
    reactions: dict[str, Reaction]
    food: frozenset[str]

    @staticmethod
    def build(reactions: list, food: list[str]) -> "CRS":
        """
        Convenience constructor.

        Each entry of `reactions` is either:
          (name, reactants, products, catalysts)  -- unit coefficients, or
          (name, reactants, products, catalysts, reactant_coeffs, product_coeffs)
        where reactant_coeffs/product_coeffs are optional dict[str, float].
        """
        rxns = {}
        species = set(food)
        for entry in reactions:
            if len(entry) == 4:
                name, reactants, products, catalysts = entry
                rc, pc = {}, {}
            else:
                name, reactants, products, catalysts, rc, pc = entry
            rxns[name] = Reaction(name, frozenset(reactants), frozenset(products),
                                   frozenset(catalysts), dict(rc), dict(pc))
            species |= set(reactants) | set(products) | set(catalysts)
        return CRS(species=frozenset(species), reactions=rxns, food=frozenset(food))


def gen(food: frozenset[str], reaction_subset) -> frozenset[str]:
    """
    gen(F0, R') = F0 union prod(R'): the species generated by a reaction
    set R' (Sec. 3) -- the food species together with EVERY product of
    EVERY reaction in R', as a flat set union.

    This is deliberately NOT an iterative reachability closure. The
    paper's Remark 3.2 is explicit that this "relational reading" is
    strictly weaker than the classical Hordijk-Steel constructive
    condition (reactions orderable so each reactant is food or a product
    of an earlier reaction): a flat union also admits reaction sets whose
    species are only *mutually* producible (e.g. r1: x -> y catalyzed by
    y, r2: y -> x catalyzed by x -- neither reactant is ever reachable by
    forward-chaining from empty/food alone, yet each is in prod(R')).
    Such mutually-dependent conservative cycles are exactly the "fragile
    circuits" this whole framework is about (Remark 3.2: a constructively
    food-generated RAF has an EMPTY fragile part -- precisely the
    degeneracy this paper's relational reading is designed to avoid).
    Do not "fix" this into an iterative closure; that would silently
    revert to the degenerate classical reading.
    """
    reactions = list(reaction_subset)
    prod = set()
    for r in reactions:
        prod |= r.products
    return frozenset(set(food) | prod)
