"""
dependency.py — The dependency DAG among fragile circuits (Sec 2.8,
Def 2.20-2.22, Prop 2.22) and the irrRAF / indecomposable-sub-RAF
correspondence (Sec 5, Theorems 5.4-5.6).

Reuses Decomposition_Theorem's decomp engine (via decomp_shim) for the
one LP-backed primitive this needs: OP(F0 u Y), the set of species
overproducible in the sub-network generated by food together with a
growing set of circuits. Everything else here (interface, the Yt
fixpoint, depth, the >- relation) is pure set/graph logic on top of that.
"""
from __future__ import annotations

import os
import sys
from dataclasses import dataclass, field

_here = os.path.dirname(os.path.abspath(__file__))
_decomp_proj = os.path.normpath(os.path.join(_here, "..", "..", "Decomposition_Theorem"))
if _decomp_proj not in sys.path:
    sys.path.insert(0, _decomp_proj)

from decomp.bridge import so_domain            # noqa: E402
from decomp.catalysts import compute_catalysts  # noqa: E402
from decomp.overproduction import compute_overproduced  # noqa: E402
from decomp.types import DecompositionResult    # noqa: E402

from .cot_bridge import TranslatedNet, closure as cot_closure
from .decomp_shim import RNShim


def _interface(circuit, shim: RNShim, F_mask: int) -> int:
    """I(Di) = species of F consumed by Di's own path reactions R*_i."""
    supp_union = 0
    for r in circuit.reaction_ids:
        supp_union |= shim.supp_raw[r]
    return supp_union & F_mask


def _produced_by(circuit, shim: RNShim) -> int:
    prod_union = 0
    for r in circuit.reaction_ids:
        prod_union |= shim.prod_raw[r]
    return prod_union


def compute_OP(net: TranslatedNet, shim: RNShim, S_full, X_mask: int, F0_mask: int) -> int:
    """
    OP(X): species overproducible in "the sub-organization GENERATED BY"
    X_mask (Def 2.18) -- i.e. the closure of X_mask under the translated
    network, not X_mask itself.

    This closure step matters: a growing circuit set Y typically triggers
    reactions whose PRODUCTS lie outside F0 u Y (e.g. D1={a,b}'s own
    reaction also produces g, which is not itself in {f,a,b}) -- without
    closing first, `so_domain` would never even give such a species a row
    in the LP (it restricts to species literally inside the mask), so it
    could never be found overproducible no matter what the flux does.
    """
    closed_names = cot_closure(net, shim.bitset_to_names(X_mask))
    closed_mask = shim.names_to_bitset(closed_names)
    domain = so_domain(closed_mask, shim, S_full)
    e_mask = compute_catalysts(domain)
    f_mask, _witnesses = compute_overproduced(domain, F0_mask, e_mask)
    return f_mask


@dataclass
class DependencyDAG:
    depth: list[int | None]          # per circuit index, None if never activated
    edges: list[tuple[int, int]]     # (i, j) meaning Di >- Dj
    activated: list[bool]            # Y_infinity membership per circuit index
    interfaces: list[int]            # I(Di) as species masks

    def is_activatable(self) -> bool:
        return all(self.activated)

    def ancestors(self, j: int) -> set[int]:
        """Anc(Dj): circuits from which Dj is reachable via >- (transitive)."""
        anc: set[int] = set()
        frontier = [i for (i, jj) in self.edges if jj == j]
        while frontier:
            i = frontier.pop()
            if i in anc:
                continue
            anc.add(i)
            frontier.extend(p for (p, q) in self.edges if q == i)
        return anc

    def minimal_circuits(self) -> list[int]:
        """Depth-1 circuits: no ancestors, interface subset F0 alone (Theorem 5.4)."""
        return [i for i, d in enumerate(self.depth) if d == 1]

    def maximal_elements(self, subset: set[int] | None = None) -> list[int]:
        """Circuits in `subset` (default: all activated) with no descendant in `subset`."""
        S = subset if subset is not None else {i for i, a in enumerate(self.activated) if a}
        has_desc = {i for (i, j) in self.edges if i in S and j in S}
        return sorted(S - has_desc)

    def is_indecomposable(self, subset: set[int] | None = None) -> bool:
        """Theorem 5.5: R(J) indecomposable iff J has a unique maximal element."""
        return len(self.maximal_elements(subset)) == 1


def build_dependency_dag(result: DecompositionResult, net: TranslatedNet, shim: RNShim, S_full,
                          F0_mask: int, *, max_rounds: int | None = None) -> DependencyDAG:
    """
    Compute the dependency DAG (Def 2.20-2.22) for `result`'s fragile
    circuits within the translated network `net` (also given as (shim, S_full)).
    """
    circuits = result.circuits
    n = len(circuits)
    interfaces = [_interface(c, shim, result.F_mask) for c in circuits]
    activated = [False] * n
    depth: list[int | None] = [None] * n
    max_rounds = max_rounds if max_rounds is not None else (n + 1)

    t = 0
    while True:
        t += 1
        Y_species = F0_mask
        for i in range(n):
            if activated[i]:
                Y_species |= circuits[i].species_mask
        OP_Yt = compute_OP(net, shim, S_full, Y_species, F0_mask)
        newly = [i for i in range(n) if not activated[i] and (interfaces[i] & ~OP_Yt) == 0]
        if not newly:
            break
        for i in newly:
            activated[i] = True
            depth[i] = t
        if all(activated) or t > max_rounds:
            break

    edges: list[tuple[int, int]] = []
    for j in range(n):
        if depth[j] is None:
            continue
        contextual_j = interfaces[j] & ~F0_mask
        if not contextual_j:
            continue
        for i in range(n):
            if i == j or depth[i] is None or not (depth[i] < depth[j]):
                continue
            if _produced_by(circuits[i], shim) & contextual_j:
                edges.append((i, j))

    return DependencyDAG(depth=depth, edges=edges, activated=activated, interfaces=interfaces)


def irrRAF_candidate_names(result: DecompositionResult, shim: RNShim, circuit_index: int) -> frozenset[str]:
    """
    The reaction-name set that Theorem 5.4 predicts is an irrRAF for a
    depth-1 (minimal) circuit: exactly its own path R*_i, read back as
    original-CRS reaction names.

    cot_translate() names a translated reaction identically to the
    original CRS reaction when it has a single catalyst, and
    "{name}__cat_{catalyst}" when it has several (one translated reaction
    per possible catalyst -- see cot_bridge.cot_translate). Strip that
    suffix and dedupe: several translated copies of the same original
    multi-catalyst reaction must collapse back to ONE original-CRS name.
    """
    circuit = result.circuits[circuit_index]
    names = set()
    for r in circuit.reaction_ids:
        tname = shim.reaction_name(r)
        base = tname.split("__cat_", 1)[0]
        names.add(base)
    return frozenset(names)
